### PR TITLE
Added dual licensing to get around WTFPL concerns.

### PR DESCRIPTION
**Pull request by SeanHayes**
My company's lawyers are doing an audit of our software dependency licenses, and they're claiming WTFPL isn't a valid license or they have some sort of problem with it.

This PR adds dual licensing, I'm hoping this can get merged in so I don't have to swap out this lib with another one.

### CODE REVIEW

**Comment by sadams** [comment]
It's fine with me. I will probably merge this and then just remove WTFPL for simplicity.

**Comment by SeanHayes** [comment]
Thank you so much!

**Comment by sadams** [comment]
No problem. I will try and publish as soon as i see if it still installs/builds with a more recent version of node...

**Comment by sadams** [comment]
@SeanHayes started down an over-engineering path but came back from the brink and published 1.0.5 with this commit: 
https://github.com/sadams/lite-url/commit/10cb29a1b38b747629bc0f1739ea4bf60d758f8a
Hope that is what you need.

**Pull request merged**
